services:
  app:
    build:
      context: .
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      ENVIRONMENT: ${ENVIRONMENT}
      SERVER_HOST: ${SERVER_HOST}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_USER: ${MAIL_SMTP_USER}
      MAIL_SMTP_PASSWORD: ${MAIL_SMTP_PASSWORD}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      ADMIN_USER_NAME: ${ADMIN_USER_NAME}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
      ADMIN_USER_PASSWORD: ${ADMIN_USER_PASSWORD}
      MESSAGING_API_TOKEN: ${MESSAGING_API_TOKEN}
      MESSAGING_PHONE_ID: ${MESSAGING_PHONE_ID}
      MESSAGING_WH_VERIFICATION_TOKEN: ${MESSAGING_WH_VERIFICATION_TOKEN}
      MESSAGING_APP_SECRET: ${MESSAGING_APP_SECRET}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    depends_on:
      postgres:
        condition: service_started
    networks:
      - tabley-network
  postgres:
    image: postgres:18-alpine3.23
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - tabley_postgres_data:/var/lib/postgresql/data
    networks:
      - tabley-network

volumes:
  tabley_postgres_data:
networks:
  tabley-network:
